<?xml version="1.0"?>
<package format="3">
  <name>crisp_ur_mujoco</name>
  <version>0.0.1</version>
  <description>MuJoCo configuration for UR robots and CRISP controllers</description>

  <maintainer email="you@example.com">ros</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>mujoco_ros2_control</exec_depend>
  <exec_depend>ur_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>