x-base: &base
  image: crisp_ur_demo:base
  build:
    context: .
    dockerfile: docker/Dockerfile.ur
    args:
      ROS_DISTRO: jazzy
    target: base

  network_mode: host
  ipc: host
  pid: host
  privileged: true

  command: /bin/bash
  tty: true
  stdin_open: true

  volumes:
    - $HOME/.Xauthority:/home/ros/.Xauthority:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev:/dev
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - ./src/onshape_keys.sh:/home/ros/onshape_keys.sh:ro
  device_cgroup_rules:
    - 'c 81:* rmw'
    - 'c 189:* rmw'
  devices:
    - "/dev/input:/dev/input"
  cap_add:
    - SYS_NICE
  environment:
    QT_X11_NO_MITSHM: 1
    DISPLAY: ${DISPLAY}
    ROS_DOMAIN_ID: 100
    RCUTILS_COLORIZED_OUTPUT: 1
    SHELL: /bin/bash
    RMW: fastdds
    FASTDDS_BUILTIN_TRANSPORTS: UDPv4
    BASH_ENV: /home/ros/onshape_keys.sh
    ONSHAPE_KEYS_FILE: /home/ros/onshape_keys.sh

  ulimits:
    rtprio: 99
    rttime: -1
    memlock: 8428281856

x-ur-overlay: &ur-overlay
  <<: *base
  image: crisp_ur_demo:ur-overlay
  build:
    context: .
    dockerfile: docker/Dockerfile.ur
    target: ur-overlay

services:
  devcontainer:
    <<: *ur-overlay

  launch_ur:
    <<: *ur-overlay
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
      source install/setup.bash &&
      export ROS_NETWORK_INTERFACE=${ROS_NETWORK_INTERFACE:-lo} &&
      RMW=${RMW:-} source src/crisp_ur_demo/scripts/setup_middleware.sh &&
      ros2 launch crisp_ur_demos ur.launch.py
      ur_type:=ur30 robot_ip:=${ROBOT_IP:-192.168.56.1} use_rviz:=True"

  launch_ursim:
    <<: *ur-overlay
    user: root
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
      source install/setup.bash &&
      export ROS_NETWORK_INTERFACE=${ROS_NETWORK_INTERFACE:-lo} &&
      RMW=${RMW:-} source src/crisp_ur_demo/scripts/setup_middleware.sh &&
      ros2 run ur_client_library start_ursim.sh -v 10.11.0 -m ur30"

  launch_zenoh_router:
    <<: *base
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
      export RMW_IMPLEMENTATION=rmw_zenoh_cpp &&
      export RUST_LOG=zenoh=info &&
      ros2 doctor -r | grep rmw_zenoh_cpp &&
      ros2 daemon stop && ros2 daemon start &&
      ros2 run rmw_zenoh_cpp rmw_zenohd"

  launch_ur_mujoco:
    <<: *ur-overlay
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
      source install/setup.bash &&
      export ROS_NETWORK_INTERFACE=${ROS_NETWORK_INTERFACE:-lo} &&
      RMW=${RMW:-} source src/crisp_ur_demo/scripts/setup_middleware.sh &&
      ros2 launch crisp_ur_mujoco ur_mujoco.launch.py
      ur_type:=ur30 use_rviz:=True show_gui:=True use_pose_broadcaster:=False"

  launch_vacuum_gripper:
    <<: *ur-overlay
    volumes:
      - $HOME/.Xauthority:/home/ros/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/onshape_keys.sh:/home/ros/onshape_keys.sh:ro
      - .:/home/ros/ros2_ws/src/crisp_ur_demo:rw
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
      colcon build --symlink-install --packages-select vaacum_gripper_description &&
      source install/setup.bash &&
      ros2 launch vaacum_gripper_description display.launch.py"

  launch_ur_vacuum_gripper:
    <<: *ur-overlay
    volumes:
      - $HOME/.Xauthority:/home/ros/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/onshape_keys.sh:/home/ros/onshape_keys.sh:ro
      - .:/home/ros/ros2_ws/src/crisp_ur_demo:rw
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
      source install/setup.bash &&
      colcon build --symlink-install --packages-select crisp_ur_mujoco vaacum_gripper_description &&
      source install/setup.bash &&
      ros2 launch crisp_ur_mujoco ur_vacuum_gripper.launch.py
      ur_type:=ur30 use_rviz:=True show_gui:=True use_pose_broadcaster:=False"

  launch_dual_ur_vacuum_gripper:
    <<: *ur-overlay
    volumes:
      - $HOME/.Xauthority:/home/ros/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/onshape_keys.sh:/home/ros/onshape_keys.sh:ro
      - .:/home/ros/ros2_ws/src/crisp_ur_demo:rw
    command: >
      bash -lc "source /opt/ros/jazzy/setup.bash &&
      source install/setup.bash &&
      colcon build --symlink-install --packages-select crisp_ur_mujoco vaacum_gripper_description &&
      source install/setup.bash &&
      ros2 launch crisp_ur_mujoco dual_ur_vacuum_gripper.launch.py
      ur_type:=ur30 use_rviz:=True show_gui:=True"
